export const mockJobData = [
  {
    id: 1,
    status: "Applied",
    company: "Samsara",
    location: "San Francisco, CA",
    title: "Software Architect ↗",
    applied: "03/05/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: 2,
    status: "Applied",
    company: "Acorns",
    location: "Irvine, CA",
    title: "Software Engineer I, Web ↗",
    applied: "03/01/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 33.6846,
    lng: -117.8265,
  },
  {
    id: 3,
    status: "Under consideration",
    company: "Anduril Industries",
    location: "Costa Mesa, CA",
    title: "Air Defense, Mission Systems Engineer ↗",
    applied: "02/21/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 33.6638,
    lng: -117.9047,
  },
  {
    id: 4,
    status: "No longer under consideration",
    company: "Lynk",
    location: "Remote",
    title: "Spacecraft Communications Engineer ↗",
    applied: "02/19/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: true,
    lat: 37.0902,
    lng: -95.7129,
  },
  {
    id: 5,
    status: "Applied",
    company: "HiveWatch",
    location: "El Segundo, CA (Hybrid)",
    title: "Software Engineer - Platform ↗",
    applied: "02/19/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: true,
    lat: 33.9192,
    lng: -118.4165,
  },
  {
    id: 6,
    status: "Under consideration",
    company: "Uber",
    location: "San Francisco, CA",
    title: "Product Manager ↗",
    applied: "01/03/2023",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: 7,
    status: "No longer under consideration",
    company: "Tesla",
    location: "Palo Alto, CA",
    title: "Electrical Engineer ↗",
    applied: "02/15/2023",
    withdrawArchive: "Withdraw | Archive",
    archived: true,
    lat: 37.4419,
    lng: -122.1430,
  },
  {
    id: 8,
    status: "Applied",
    company: "Intelsat",
    location: "Boston, MA",
    title: "Full Stack Intern ↗",
    applied: "02/29/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 42.3601,
    lng: -71.0589,
  },
  {
    id: 9,
    status: "Applied",
    company: "Maxar",
    location: "McClean, VA",
    title: "Front-End Software Developer ↗",
    applied: "02/29/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 38.9339,
    lng: -77.1773,
  },
  {
    id: 10,
    status: "Under consideration",
    company: "Zipline",
    location: "South San Francisco, CA",
    title: "Software Automation Engineer ↗",
    applied: "02/28/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 37.6547,
    lng: -122.4077,
  },
  {
    id: 11,
    status: "No longer under consideration",
    company: "L3Harris",
    location: "El Segundo, CA",
    title: "Systems Engineer ↗",
    applied: "02/28/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: true,
    lat: 33.9192,
    lng: -118.4165,
  },
  {
    id: 12,
    status: "Applied",
    company: "Sonos",
    location: "San Diego, CA",
    title: "Audio Engineer ↗",
    applied: "02/17/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 32.7157,
    lng: -117.1611,
  },
  {
    id: 13,
    status: "Applied",
    company: "Prelim",
    location: "Los Angeles, CA",
    title: "Sales Engineer ↗",
    applied: "02/27/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 34.0549,
    lng: -118.2426,
  },
  {
    id: 14,
    status: "Applied",
    company: "Amazon",
    location: "Redmond, WA",
    title: "Systems Development Engineer ↗",
    applied: "02/27/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 47.6740,
    lng: -122.1215,
  },
  {
    id: 15,
    status: "Under consideration",
    company: "Amazon",
    location: "Redmond, WA",
    title: "Integration & Test Engineer ↗",
    applied: "02/27/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 47.6740,
    lng: -122.1215,
  },
  {
    id: 16,
    status: "No longer under consideration",
    company: "iridium",
    location: "Chandler, AZ",
    title: "Account Manager ↗",
    applied: "02/21/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 33.3062,
    lng: -111.8413,

  },
  {
    id: 17,
    status: "Applied",
    company: "RocketLab",
    location: "Long Beach, CA",
    title: "RF Systems Engineer ↗",
    applied: "02/20/2024",
    withdrawArchive: "Withdraw | Archive",
    archived: false,
    lat: 33.7701,
    lng: -118.1937,
  },
];